name: Build Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: github.event.repository.name
  DOCKER_HUB_REPO: ebonian/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
      - name: Docker login using Docker Hub credentials
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Deploy Docker Image
        run: |
            docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_HUB_REPO }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.DOCKER_HUB_REPO }}/${{ env.IMAGE_NAME }}
